-------------------------------------------------------------------------------
Test set: TestCases
-------------------------------------------------------------------------------
Tests run: 20, Failures: 8, Errors: 0, Skipped: 0, Time elapsed: 4.161 s <<< FAILURE! - in TestCases
basicChecks  Time elapsed: 0.04 s
registerCollege  Time elapsed: 3.21 s
registerCollegeException  Time elapsed: 0.032 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: method is not throwing exception, even when we are passing null objects while adding an college ==> Unexpected exception type thrown, expected: <exceptions.CollegeException> but was: <java.lang.IllegalArgumentException>
	at TestCases.registerCollegeException(TestCases.java:80)

getCollegeFromCollegeId  Time elapsed: 0.049 s
getCollegeFromCollegeIdException  Time elapsed: 0.022 s
getAllCollege  Time elapsed: 0.404 s
getAllCollegeException  Time elapsed: 0.014 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: getAllCollege method is not throwing exception even non of the college is in database ==> Expected exceptions.CollegeException to be thrown, but nothing was thrown.
	at TestCases.getAllCollegeException(TestCases.java:169)

registerStudentToCollege  Time elapsed: 0.026 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "obj" is null
	at TestCases.registerStudentToCollege(TestCases.java:194)

registerStudentToCollegeException  Time elapsed: 0.036 s
getAllStudentsFromCollegeId  Time elapsed: 0.024 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "students" is null
	at TestCases.getAllStudentsFromCollegeId(TestCases.java:245)

getAllStudentsFromCollegeIdException  Time elapsed: 0.014 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: getAllStudentsFromCollegeId method is not throwing exception even non of the student register to the college ==> Expected exceptions.StudentException to be thrown, but nothing was thrown.
	at TestCases.getAllStudentsFromCollegeIdException(TestCases.java:272)

registerStudent  Time elapsed: 0.01 s
registerStudentException  Time elapsed: 0.008 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: method is not throwing exception, even when we are passing null objects while adding an college ==> Unexpected exception type thrown, expected: <exceptions.CollegeException> but was: <java.lang.IllegalArgumentException>
	at TestCases.registerStudentException(TestCases.java:329)

getStudentFromCollegeId  Time elapsed: 0.034 s
getStudentFromCollegeIdException  Time elapsed: 0.015 s
getAllActiveStudents  Time elapsed: 0.132 s
getAllActiveStudentsException  Time elapsed: 0.016 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: getAllActiveStudents method is not throwing exception even non of the student register ==> Expected exceptions.StudentException to be thrown, but nothing was thrown.
	at TestCases.getAllActiveStudentsException(TestCases.java:429)

getCollegeFromStudentId  Time elapsed: 0.031 s
getCollegeFromStudentIdsException  Time elapsed: 0.017 s  <<< FAILURE!
org.opentest4j.MultipleFailuresError: 
Multiple Failures (1 failure)
	org.opentest4j.AssertionFailedError: getCollegeFromStudentIdsException method is not throwing Exception when unknown StudentId/roll pass ==> Unexpected exception type thrown, expected: <exceptions.StudentException> but was: <exceptions.CollegeException>
	at TestCases.getCollegeFromStudentIdsException(TestCases.java:477)

buildScore  Time elapsed: 0.001 s
